version: '3'
services:
  node:
    build: .
    container_name: node
    restart: on-failure
    volumes: 
      - ./src:/usr/src/src
      - ./LOGS:/usr/src/LOGS
    command: ["./wait-for.sh", "${POSTGRES_HOST}:${POSTGRES_PORT}", "--", "npm", "start"]
    ports: 
      - ${PORT}:${PORT}
    networks: 
      - user_defined_bridge
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=${DOCKER_POSTGRES_HOST}
      - POSTGRES_PORT=${DOCKER_POSTGRES_PORT}
  postgres:
    container_name: postgres
    build: ./database/
    environment:
      - POSTGRES_PASSWORD=postgres_password
    networks: 
      - user_defined_bridge
    volumes: 
      - ./database/postgres_data:/var/lib/postgresql/data/
      - ./database/postrgres_log:/var/log/
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB} 
networks: 
  user_defined_bridge:
    driver: bridge
